#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agregar_usuario
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="uesgym")]
	public partial class DBuesGymDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Inserttipos_cliente(tipos_cliente instance);
    partial void Updatetipos_cliente(tipos_cliente instance);
    partial void Deletetipos_cliente(tipos_cliente instance);
    partial void Insertusuario(usuario instance);
    partial void Updateusuario(usuario instance);
    partial void Deleteusuario(usuario instance);
    #endregion
		
		public DBuesGymDataContext() : 
				base(global::Agregar_usuario.Properties.Settings.Default.uesgymConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBuesGymDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBuesGymDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBuesGymDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBuesGymDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<tipos_cliente> tipos_clientes
		{
			get
			{
				return this.GetTable<tipos_cliente>();
			}
		}
		
		public System.Data.Linq.Table<usuario> usuarios
		{
			get
			{
				return this.GetTable<usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarNuevoCliente")]
		public int insertarNuevoCliente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(110)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_tipo_cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(12)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(12)")] string telefono_de_emergencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string status_membresia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_inicio_membresia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha_corte_membresia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string certificado_medico)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, id_tipo_cliente, correo, direccion, telefono, telefono_de_emergencia, status_membresia, fecha_inicio_membresia, fecha_corte_membresia, certificado_medico);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private System.Nullable<int> _id_tipo_cliente;
		
		private string _nombre;
		
		private string _correo;
		
		private string _direccion;
		
		private string _telefono;
		
		private string _telefono_de_emergencia;
		
		private string _status_membresia;
		
		private System.DateTime _fecha_inicio_membresia;
		
		private System.DateTime _fecha_corte_membresia;
		
		private string _certificado_medico;
		
		private EntityRef<tipos_cliente> _tipos_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Onid_tipo_clienteChanging(System.Nullable<int> value);
    partial void Onid_tipo_clienteChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Ontelefono_de_emergenciaChanging(string value);
    partial void Ontelefono_de_emergenciaChanged();
    partial void Onstatus_membresiaChanging(string value);
    partial void Onstatus_membresiaChanged();
    partial void Onfecha_inicio_membresiaChanging(System.DateTime value);
    partial void Onfecha_inicio_membresiaChanged();
    partial void Onfecha_corte_membresiaChanging(System.DateTime value);
    partial void Onfecha_corte_membresiaChanged();
    partial void Oncertificado_medicoChanging(string value);
    partial void Oncertificado_medicoChanged();
    #endregion
		
		public cliente()
		{
			this._tipos_cliente = default(EntityRef<tipos_cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_cliente", DbType="Int")]
		public System.Nullable<int> id_tipo_cliente
		{
			get
			{
				return this._id_tipo_cliente;
			}
			set
			{
				if ((this._id_tipo_cliente != value))
				{
					if (this._tipos_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_tipo_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_cliente = value;
					this.SendPropertyChanged("id_tipo_cliente");
					this.Onid_tipo_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(130) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_de_emergencia", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string telefono_de_emergencia
		{
			get
			{
				return this._telefono_de_emergencia;
			}
			set
			{
				if ((this._telefono_de_emergencia != value))
				{
					this.Ontelefono_de_emergenciaChanging(value);
					this.SendPropertyChanging();
					this._telefono_de_emergencia = value;
					this.SendPropertyChanged("telefono_de_emergencia");
					this.Ontelefono_de_emergenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_membresia", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string status_membresia
		{
			get
			{
				return this._status_membresia;
			}
			set
			{
				if ((this._status_membresia != value))
				{
					this.Onstatus_membresiaChanging(value);
					this.SendPropertyChanging();
					this._status_membresia = value;
					this.SendPropertyChanged("status_membresia");
					this.Onstatus_membresiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inicio_membresia", DbType="Date NOT NULL")]
		public System.DateTime fecha_inicio_membresia
		{
			get
			{
				return this._fecha_inicio_membresia;
			}
			set
			{
				if ((this._fecha_inicio_membresia != value))
				{
					this.Onfecha_inicio_membresiaChanging(value);
					this.SendPropertyChanging();
					this._fecha_inicio_membresia = value;
					this.SendPropertyChanged("fecha_inicio_membresia");
					this.Onfecha_inicio_membresiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_corte_membresia", DbType="Date NOT NULL")]
		public System.DateTime fecha_corte_membresia
		{
			get
			{
				return this._fecha_corte_membresia;
			}
			set
			{
				if ((this._fecha_corte_membresia != value))
				{
					this.Onfecha_corte_membresiaChanging(value);
					this.SendPropertyChanging();
					this._fecha_corte_membresia = value;
					this.SendPropertyChanged("fecha_corte_membresia");
					this.Onfecha_corte_membresiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificado_medico", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string certificado_medico
		{
			get
			{
				return this._certificado_medico;
			}
			set
			{
				if ((this._certificado_medico != value))
				{
					this.Oncertificado_medicoChanging(value);
					this.SendPropertyChanging();
					this._certificado_medico = value;
					this.SendPropertyChanged("certificado_medico");
					this.Oncertificado_medicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipos_cliente_cliente", Storage="_tipos_cliente", ThisKey="id_tipo_cliente", OtherKey="id_tipo_cliente", IsForeignKey=true)]
		public tipos_cliente tipos_cliente
		{
			get
			{
				return this._tipos_cliente.Entity;
			}
			set
			{
				tipos_cliente previousValue = this._tipos_cliente.Entity;
				if (((previousValue != value) 
							|| (this._tipos_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipos_cliente.Entity = null;
						previousValue.clientes.Remove(this);
					}
					this._tipos_cliente.Entity = value;
					if ((value != null))
					{
						value.clientes.Add(this);
						this._id_tipo_cliente = value.id_tipo_cliente;
					}
					else
					{
						this._id_tipo_cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipos_cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipos_clientes")]
	public partial class tipos_cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipo_cliente;
		
		private string _tipo_cliente;
		
		private EntitySet<cliente> _clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipo_clienteChanging(int value);
    partial void Onid_tipo_clienteChanged();
    partial void Ontipo_clienteChanging(string value);
    partial void Ontipo_clienteChanged();
    #endregion
		
		public tipos_cliente()
		{
			this._clientes = new EntitySet<cliente>(new Action<cliente>(this.attach_clientes), new Action<cliente>(this.detach_clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipo_cliente
		{
			get
			{
				return this._id_tipo_cliente;
			}
			set
			{
				if ((this._id_tipo_cliente != value))
				{
					this.Onid_tipo_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_cliente = value;
					this.SendPropertyChanged("id_tipo_cliente");
					this.Onid_tipo_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_cliente", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string tipo_cliente
		{
			get
			{
				return this._tipo_cliente;
			}
			set
			{
				if ((this._tipo_cliente != value))
				{
					this.Ontipo_clienteChanging(value);
					this.SendPropertyChanging();
					this._tipo_cliente = value;
					this.SendPropertyChanged("tipo_cliente");
					this.Ontipo_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipos_cliente_cliente", Storage="_clientes", ThisKey="id_tipo_cliente", OtherKey="id_tipo_cliente")]
		public EntitySet<cliente> clientes
		{
			get
			{
				return this._clientes;
			}
			set
			{
				this._clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.tipos_cliente = this;
		}
		
		private void detach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.tipos_cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.usuarios")]
	public partial class usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_usuario;
		
		private string _nombre_usuario;
		
		private System.Data.Linq.Binary _contraseña;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_usuarioChanging(int value);
    partial void Onid_usuarioChanged();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void OncontraseñaChanging(System.Data.Linq.Binary value);
    partial void OncontraseñaChanged();
    #endregion
		
		public usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_usuario
		{
			get
			{
				return this._id_usuario;
			}
			set
			{
				if ((this._id_usuario != value))
				{
					this.Onid_usuarioChanging(value);
					this.SendPropertyChanging();
					this._id_usuario = value;
					this.SendPropertyChanged("id_usuario");
					this.Onid_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
